const challengeDays = [
  [1,"Bodyweight Tabata Workout","TiRG-hfXzvM",5,"b5aefcc2","workout","BRAND NEW"],[2,"No Gym Needed Six Pack Abs Workout Anywhere","SLoC7b8xNRk",6,"54cde28a","workout"],[3,"Burn Belly Fat, 20 Minutes Dumbbells Only","6Zc6sOv4NX4",7,"a5e537b3","workout"],[4,"No Gym Needed “Hella Reps” 6-Pack Ab Workout","KMWNaSjjgZg",8,"0e6caaaa","workout"],[5,"20 Minute Intense Full Body Dumbbell HIIT Workout","6oqMS-ZdJ0o",9,"7763352f","workout"],[6,"Rest & recover",null,null,null,"rest"],[7,"You vs the Pros: Full Body Fat-Burning Challenge","OJumh9OgFyM",11,"c81b78fe","workout","CHALLENGE DAY"],[8,"No Gym Needed Jump Rope Fat Loss Workout","lDkXGw9iO-o",12,"069f19d1","workout"],[9,"6 Pack Abs Home Workout, No Equipment Needed","sg_1Xs8EmHk",13,"5a0fe145","workout"],[10,"Burn Fat Quick & Easy, Dumbbells Only Workout","G3CjmT9gvbQ",14,"67d31ab4","workout"],[11,"8 Minutes Only, Burn Fat Every Morning","EOHFBO7Ay_4",15,"67c283f8","workout"],[12,"The 7 Best Exercises to Lose Belly Fat Fast","t5fOwCUqwHQ",16,"30ce4ead","workout"],[13,"Rest & recover",null,null,null,"rest"],[14,"Full Body Pump Up Dumbbell Workout Challenge","toxbaJD4SvA",18,"f1b20103","workout","CHALLENGE DAY"],[15,"Morning Routine: Six Pack Abs Follow Along","4zM6fOt0nCI",19,"7dced1ac","workout"],[16,"No Gym Needed Full Body Bodyweight Workout","7zqa1zqXZ1Y",20,"d439466c","workout"],[17,"20 Minute Full Body Dumbbells Only Workout","y4VI84Kqew4",21,"0e94ef3a","workout"],[18,"Fighter Abs: The MMA Core Conditioning Workout","kh700GP3WYo",22,"dfea7f12","workout"],[19,"The 30-30 Dumbbell Only HIIT Workout","8h8z5dG9rLg",23,"3053fd72","workout"],[20,"Rest & recover",null,null,null,"rest"],[21,"300 Reps! Full Body Plateau Busting Challenge!","ozDUBU9Rhmc",25,"b7786a67","workout","CHALLENGE DAY"],[22,"MMA Bodyweight HIIT Workout","f3OSXIxc2cA",26,"ae902979","workout"],[23,"The Five-15-Four Full Body Dumbbell Circuit","Mb-ztIQDvlw",27,"3b4652c5","workout"],[24,"Six Minute Six-Pack Abs Workout","q6iBgeFLfNg",28,"9cd98760","workout"],[25,"The Perfect Set: 450 Rep Full Body Dumbbell Workout","rZ7h4G_C_xI",29,"8dc71bb4","workout"],[26,"Strongman Abs Workout for Strong, Sculpted Abs","RJb0bjXTaJQ",30,"cad9f988","workout"],[27,"Rest & recover",null,null,null,"rest"],[28,"Dumbbell AMRAP Final Challenge","yZZJ_WbXnfw",32,"b4e12207","workout","FINAL CHALLENGE"]
].map(([day,title,video,page,hash,type,tag]) => ({day,title,video,page,hash,type,tag}));

const imageFor = day => day.hash ? `assets/challenge/page-${String(day.page).padStart(2,"0")}-background.webp` : "";
const completed = new Set(JSON.parse(localStorage.getItem("challenge-completed") || "[]"));
const grid = document.querySelector("#day-grid");
const schedule = document.querySelector("#challenge-calendar");
const detail = document.querySelector("#challenge-detail");
const detailContent = document.querySelector("#detail-content");

function renderGrid(filter = "all") {
  grid.innerHTML = challengeDays.filter(day => filter === "all" || day.type === filter).map(day => day.type === "rest" ? `
    <article class="challenge-card rest-card"><span class="card-number">${String(day.day).padStart(2,"0")}</span><span class="rest-mark">↻</span><div><small>DAY ${day.day} · RECOVERY</small><h3>Rest & recover</h3><p>Earned, not optional.</p></div>
  </article>` : `
    <article class="challenge-card ${completed.has(day.day) ? "complete" : ""}"><a class="card-art" href="28-challenge.html?day=${day.day}"><img src="${imageFor(day)}" alt="Day ${day.day}: ${day.title}"><b>${String(day.day).padStart(2,"0")}</b><i>▶</i>${day.tag ? `<em>${day.tag}</em>` : ""}</a><div class="card-info"><small>DAY ${day.day} · WORKOUT</small><h3><a href="28-challenge.html?day=${day.day}">${day.title}</a></h3><footer><a href="28-challenge.html?day=${day.day}">View workout ↗</a><button class="complete-toggle" data-day="${day.day}" aria-label="Mark day ${day.day} complete">${completed.has(day.day) ? "✓" : ""}</button></footer></div></article>`).join("");
  grid.querySelectorAll(".complete-toggle").forEach(button => button.addEventListener("click", event => { event.preventDefault(); event.stopPropagation(); const day = Number(button.dataset.day); completed.has(day) ? completed.delete(day) : completed.add(day); localStorage.setItem("challenge-completed", JSON.stringify([...completed])); renderGrid(filter); updateProgress(); }));
}
function updateProgress() { document.querySelector("#progress-label").textContent = `${completed.size} / 28 complete`; document.querySelector("#progress-bar").style.width = `${completed.size / 28 * 100}%`; }
function showSchedule() { schedule.hidden = false; detail.hidden = true; document.title = "28 Day Challenge | Fitness & Nutrition"; }
function showDetail(day) {
  schedule.hidden = true; detail.hidden = false; const rest = day.type === "rest";
  document.title = `Day ${day.day} | 28 Day Challenge`;
  detailContent.innerHTML = rest ? `<div class="rest-detail"><span class="rest-mark">↻</span><p class="challenge-kicker">Day ${day.day} · Recovery</p><h1>Rest is part<br><em>of the work.</em></h1><p>Use today to recover, refuel, and let your body adapt. You’ve earned it.</p><a class="challenge-primary" href="28-challenge.html">Return to schedule ↗</a></div>` : `<div class="detail-hero"><img src="${imageFor(day)}" alt="Day ${day.day} artwork"><div><p class="challenge-kicker">Day ${String(day.day).padStart(2,"0")} · Follow-along workout</p><h1>${day.title}</h1><p>Follow along. Stay consistent. Leave stronger.</p><a class="challenge-primary" href="https://www.youtube.com/watch?v=${day.video}" target="_blank" rel="noopener">Open on YouTube ↗</a></div></div><div class="video-block"><p class="challenge-kicker">Your session</p><h2>Press play.</h2><div class="video-container"><iframe src="https://www.youtube.com/embed/${day.video}?rel=0" title="${day.title}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div></div>`;
}

document.querySelectorAll(".challenge-filters button").forEach(button => button.addEventListener("click", () => { document.querySelectorAll(".challenge-filters button").forEach(item => item.classList.remove("selected")); button.classList.add("selected"); renderGrid(button.dataset.filter); }));
window.addEventListener("popstate", () => { const day = Number(new URLSearchParams(location.search).get("day")); day ? showDetail(challengeDays.find(item => item.day === day) || challengeDays[0]) : showSchedule(); });
renderGrid(); updateProgress();
const initialDay = Number(new URLSearchParams(location.search).get("day")); if (initialDay) showDetail(challengeDays.find(item => item.day === initialDay) || challengeDays[0]);
